# Generated by Django 5.0 on 2023-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.IntegerField(default=25)),
                ('rest_time', models.IntegerField(default=5)),
            ],
        ),
    ]
